name: Convert README to Word
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'docs/images/**'

jobs:
  convert-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Create output directories
        run: |
          mkdir -p output/word
          mkdir -p temp

      - name: Prepare README and images
        run: |
          cp README.md temp/
          cp -r docs/images temp/
          cd temp
          sed -i 's|docs/images/|images/|g' README.md

      - name: Convert README to DOCX
        working-directory: temp
        run: |
          pandoc README.md \
            -f markdown \
            -t docx \
            --toc \
            -o "../output/word/README.docx"

      - name: List generated files
        run: |
          echo "Generated DOCX files:"
          ls -l output/word/

      - name: Upload Word document
        uses: actions/upload-artifact@v4
        with:
          name: readme-word
          path: output/word/README.docx
          retention-days: 30