name: Convert README to Word
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'docs/images/**'

jobs:
  convert-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Pandoc and required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            librsvg2-bin

      - name: Create output directories
        run: |
          mkdir -p output/word
          mkdir -p temp/images

      - name: Prepare README and images
        run: |
          # Copier le README
          cp README.md temp/
          
          # Copier les images
          cp -r docs/images/* temp/images/
          
          # Ajuster les chemins des images dans le README
          cd temp
          sed -i 's|docs/images/|images/|g' README.md

      - name: Create reference.docx
        run: |
          pandoc -o reference.docx --print-default-data-file reference.docx

      - name: Convert README to DOCX with images
        working-directory: temp
        run: |
          pandoc README.md \
            -f markdown \
            -t docx \
            --toc \
            --wrap=none \
            --reference-doc=../reference.docx \
            --extract-media=. \
            -o "../output/word/README.docx"

      - name: Upload Word document
        uses: actions/upload-artifact@v4
        with:
          name: readme-word
          path: output/word/README.docx
          retention-days: 30