name: Convert README to PDF
on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'docs/images/**'


jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare directory
        run: |
          mkdir -p output

      - name: Convert README to PDF
        uses: pandoc/pandoc-action@v1
        with:
          args: >-
            README.md
            --output=output/README.pdf
            --from=markdown
            --to=pdf
            --pdf-engine=xelatex
            --variable=geometry:margin=1in
            --toc

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: README
          path: output/README.pdf
